spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://admin.cy6doy34twwm.ap-northeast-2.rds.amazonaws.com/team012?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: admin
#    password: adminhsj15!
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 766725484707-c10etukbl387vffqcamrq025lhc30mil.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true